bsp: Use esp_lvgl_port for esp-box bsp
espressif/esp-bsp pull request #110
Opened 2022-12-30 07:33 UTC by wujiangang

Partially close #106, since the BSP for esp-box is needed at the first stage. If some modifications are needed, please update and commit directly.

2022-12-30 07:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/esp-bsp?pullRequest=110) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/esp-bsp?pullRequest=110) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/esp-bsp?pullRequest=110) it.</sub>

2023-01-03 10:32 UTC, espzav reviewed
Thank you for modify this BSP for using LVGL port! Great work! I left some comments and please don't forget increase the version of this component.

2023-01-03 10:32 UTC, espzav commented on esp-box/esp-box.c
> +
Check if `disp != NULL` before call the next function.

2023-01-03 10:32 UTC, espzav commented on esp-box/esp-box.c
> +    bsp_display_indev_init(disp);
Return `NULL`, when this function fails (returns `NULL`).

2023-01-03 11:14 UTC, espzav approved these changes
Thank you. LGTM

2023-01-03 11:15 UTC, espzav requested changes
Please, increase the component version in idf_component.yml

2023-01-03 11:29 UTC, wujiangang commented
> Please, increase the component version in idf_component.yml

I want to increase the version after #101 and #113, or each PR needs to increase a minor version?

2023-01-03 11:35 UTC, espzav commented
> I want to increase the version after #101 and #113, or each PR needs to increase a minor version?

If the version is not increased, the component will not be updated in IDF Component Registry. It's recommended increase version after each change (each PR). Some PR can take more time.

2023-01-03 11:55 UTC, espzav approved these changes
Thank you. LGTM

2023-01-05 07:38 UTC, merged