add lvgl task size and task priority config for lvgl task
espressif/esp-bsp pull request #190
Opened 2023-07-14 12:28 UTC by Jerry-ESP

# ESP-BSP Pull Request checklist

In some application, the default 4096 lvgl task stack size is not enough, so we need config this task stack size

# Change
Add a menuconfig entry to config the lvgl task stack size and priority

2023-07-14 12:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/esp-bsp?pullRequest=190) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/esp-bsp?pullRequest=190) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/esp-bsp?pullRequest=190) it.</sub>

2023-07-14 13:55 UTC, espzav requested changes
I think, that this is bad. Because user doesn't need use init macro and when he calls init with own structure, then KConfig changes will be confusing.
We want to add new function in BSP API, which will have param with  configuration structure for display initialization, where will be all params (whole structure) for LVGL port. We have it in plan.

2023-07-20 13:49 UTC, espzav commented
Here is PR for ESP-BOX BSP, which adding function for initialize display with params: https://github.com/espressif/esp-bsp/pull/192
Is it ok for you?

2023-07-21 06:20 UTC, espressif2022 commented
> Here is PR for ESP-BOX BSP, which adding function for initialize display with params: #192 Is it ok for you?

@Jerry-ESP ，I think it's ok. there add an independent interface.

2023-07-21 06:36 UTC, Jerry-ESP commented
> Here is PR for ESP-BOX BSP, which adding function for initialize display with params: #192 Is it ok for you?

Yes, it is OK, thanks a lot, wait for your PR merged.

2023-07-21 07:46 UTC, closed without merging