add esp32-s3-korvo-1 audio and sd card
espressif/esp-bsp pull request #282
Opened 2024-01-24 11:18 UTC by pborcin

# ESP-BSP Pull Request checklist

- [ ] Version of modified component bumped
- [ ] CI passing

2024-01-24 11:18 UTC, pborcin commented
@tore-espressif @espzav PTAL

2024-01-24 15:48 UTC, tore-espressif reviewed
Thank you very much for the update @pborcin , I'd like to test on HW before we proceed with this MR.

2 more things:
1. This BSP is not build in any CI job. You should add `sdkconfig.bsp.esp32_s3_korvo_1` file to examples that should work on this BSP. Eg examples/audio
2. Audio for v4.4 will fail to build. Could you please have a look at that too?

2024-01-24 15:48 UTC, tore-espressif commented on bsp/esp32_s3_korvo_1/idf_component.yml
> +    version: "1.0.3"
Let's allow automatic bugfix updates
```suggestion
    version: "~1.0.3"
```

2024-01-24 15:48 UTC, tore-espressif commented on bsp/esp32_s3_korvo_1/esp32_s3_korvo_1_idf5.c
> +        .slot_cfg = I2S_TDM_PHILIP_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_16BIT, I2S_SLOT_MODE_STEREO, I2S_TDM_SLOT0 | I2S_TDM_SLOT1 | I2S_TDM_SLOT2),\
This TDM configuration is not usual. Could you provide a docs block explaining the settings?

2024-01-24 15:48 UTC, tore-espressif commented on bsp/esp32_s3_korvo_1/esp32_s3_korvo_1_idf4.c
>  #include "esp_err.h"
This file was probably not updated and will fail to compile.

2024-01-25 13:17 UTC, espzav reviewed
@pborcin Thank you for this PR. Good job! I didn't test it, I haven't got a board. Code LGTM Left only one comment and you should **increase the version of component**.

2024-02-15 09:03 UTC, pborcin commented
@tore-espressif @espzav PTAL

2024-02-15 10:09 UTC, tore-espressif commented on bsp/esp32_s3_korvo_1/include/bsp/esp32_s3_korvo_1.h
> + * For speaker initialization use bsp_audio_codec_speaker_init() which is inside initialize I2S with bsp_audio_init().
Nitpick: Typo?
```suggestion
 * For speaker initialization use bsp_audio_codec_speaker_init() which in turn initializes I2S with bsp_audio_init().
```

2024-02-15 10:09 UTC, tore-espressif commented on bsp/esp32_s3_korvo_1/include/bsp/esp32_s3_korvo_1.h
Could you also please add capabilities defines? Like this: https://github.com/espressif/esp-bsp/blob/master/bsp/esp-box-3/include/bsp/esp-box-3.h#L30

2024-02-15 10:09 UTC, tore-espressif commented on bsp/esp32_s3_korvo_1/include/bsp/esp32_s3_korvo_1.h
> +const audio_codec_data_if_t *bsp_audio_get_codec_itf_spk(void);
@espzav It seems that when we added `bsp_audio_get_codec_itf` function to BSP APIs, we did not consider the scenarion where 2 I2S peripherals are used for playback and recording. What do you think about this new function?

2024-02-15 10:09 UTC, tore-espressif commented on bsp/esp32_s3_korvo_1/include/bsp/esp32_s3_korvo_1.h
> +const audio_codec_data_if_t *bsp_audio_get_codec_itf_spk(void);
Same applies to `bsp_audio_init` where we pass I2S config only for 1 I2S peripheral 😮‍💨

2024-02-15 14:09 UTC, tore-espressif commented on bsp/esp32_s3_korvo_1/include/bsp/esp32_s3_korvo_1.h
Thanks, could you add _all_ the capabilities macros? And define them as '0' in they are not supported? https://github.com/espressif/esp-bsp/blob/master/bsp/esp32_s3_usb_otg/include/bsp/esp32_s3_usb_otg.h#L25

2024-02-16 10:51 UTC, tore-espressif commented
@pborcin I tried on HW and my audio playback is not working (no sound). Is there anything else I need to do to make it work?

2024-02-28 08:45 UTC, tore-espressif approved these changes
LGTM! @espzav should we wait for your review?

2024-02-28 08:51 UTC, espzav approved these changes
LGTM

2024-02-28 09:07 UTC, tore-espressif requested changes
@pborcin plese bump the version before merging!

2024-02-28 09:07 UTC, tore-espressif commented on bsp/esp32_s3_korvo_1/idf_component.yml
>      public: true
@pborcin Please update version (line 1) to 1.1.0

2024-02-29 13:40 UTC, tore-espressif approved these changes

2024-02-29 13:41 UTC, merged